services:
  kittenbark_tg:
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: kittenbark_tg
    # network_mode: host
    # env_file:
    #   - .env
    #   - ${HOME}/.env
    # volumes:
    #   - ${TG_LOCAL_API_STORAGE}:${TG_LOCAL_API_STORAGE}
    # restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
